version: '3.8'

services:
  redis_cache:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./execution:/app/execution
      - ./tmp:/app/tmp
    restart: unless-stopped
    depends_on:
      - redis_cache

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: "/api"
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  redis_data: {}